"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = " "
detect_files = ["package.json"]

[package]
disabled = true

[cmd_duration]
min_time = 2_000
show_milliseconds = false
